spring:
 application:
  name: back
 datasource:
  url: jdbc:oracle:thin:@115.90.212.18:10000:XE
  username: C##QOWNDUD12
  password: rkdgustjd123
  driver-class-name: oracle.jdbc.driver.OracleDriver
 mvc:
  static-path-pattern: /uploads/**
 web:
  resources:
   static-locations: file:uploads/
 servlet:
  multipart:
   max-file-size: 100MB
   max-request-size: 100MB
  
server:
 port: 8081
 
mybatis:
  configuration:
    jdbc-type-for-null: VARCHAR
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.kh.pcar.back.*.model.vo, com.kh.pcar.back.*.model.dto
  mapper-locations: classpath:mapper/**/*.xml
  
  
jwt:
 secret: H7oIaBujRo6fA/a0wdk09iY6STECQZbemMj8bcs5xBMzd0IYxzT+hNQd+fgXvsyz3qHF3DIwuYXUE9m7w5tkDw==
 
naver:
  client:
    id: Kki4fyVYcYf_zkU2HAq8
    secret: q6k43VptHS
  redirect:
    url: http://localhost:8081/members/naver/callback   
    
kakao:
  client:
    id: 9ab6eed4ca0b2e40761693da623540b9
  redirect:
    url: http://localhost:5173/members/kakao/callback 
charge:
  client:
    id: serviceKey=379f167eb3f41af06081d27f407899ed21955011b09d34a54e3519d8544a89cb
  redirect:
    url: https://api.odcloud.kr/api/15039545/v1/uddi:f8f879ad-68cf-40fb-8ccc-cb36eaf1baca?